# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bb5390ae3bf6217c044f1f4d9ad7ce7b9c2e32d83e32bc78f726a102150edac1f628605855a8c782a6af7da5ad75922e47b7db4fa4920665a218ad8e3e215a1

test:
  secret_key_base: 97c7d85a76f81de794776934cfb1ca6a61d44dbde205e8aa3c453c402be81a99fb7d5444eb3e1caea34a16931d40643905cbed6106825cbe0edd6e717f20d264

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
